name: Mobilewright Test
on:
    push:
        branches: [main]
    
jobs:
    ios-test:
        runs-on: macos-14
        steps:
            - uses: actions/checkout@v4
            - run: ls -la
            - uses: actions/setup-node@v4
              with:
                node-version: 22
            - run: |
                npm ci
                ls -la
            - name: Booting simulator that mentioned in config file
              run: |
                xcrun simctl boot 'iPhone 16'
            - name: Run mobilewright test
              run: npx mobilewright test