name: Mobilewright Test
on:
    push:
        branches: [main]
    
jobs:
    ios-test:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 22
            - run: |
                npm ci
                ls -la
            - name: Run mobilewright test
              run: npx mobilewright test